apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blockeeper-service
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: blockeeper-service
    spec:
      containers:
      - name: blockeeper-service
        image: centralitycontainerregistry-on.azurecr.io/centrality/blockeeper:1.0.<number>
        env:
          - name: ROOT_URL
            value: "https://<env_prefix>blockeeper.centrality.ai"
          - name: PORT
            value: 8080
          - name: MONGO_URL
            value: mongodb://mongo/blockeeper
          - name: METEOR_SETTINGS
            valueFrom:
              configMapKeyRef:
                key: appsettings.json
                name: blockeeper-settings
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
      imagePullSecrets:
      - name: registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: blockeeper-service
  labels:
    app: blockeeper-service
spec:
  ports:
  - port: 8080
    name: frontend
  selector:
    app: blockeeper-service
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: blockeeper-service
  labels:
    app: blockeeper-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: blockeeper-service
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80