export const SET_ACCOUNTS = 'SET_ACCOUNTS'

export const SET_ACTIVE_PROFILE = 'SET_ACTIVE_PROFILE'
export const SET_LANGUAGE='SET_LANGUAGE'
export const SET_EXCHANGE='SET_EXCHANGE'
export const SET_SEARCH_BLOCK='SET_SEARCH_BLOCK'