export const ACCOUNTS_RECEIVED = 'ACCOUNTS_RECEIVED'
export const ACCOUNTS_EXCHANGERATE_RECEIVED = 'ACCOUNTS_EXCHANGERATE_RECEIVED'

export const PROFILES_ACTIVE_RECEIVED = 'PROFILES_ACTIVE_RECEIVED'
export const PROFILES_BALANCE_RECEIVED = 'PROFILES_BALANCE_RECEIVED'

export const NAVIGATION_LOCALE_CHANGED = 'NAVIGATION_LOCALE_CHANGED'
export const NAVIGATION_TXFILTER_CHANGED = 'NAVIGATION_TXFILTER_CHANGED'