#!groovy
pipeline {
  agent {
    label 'linux'
  }

  environment {
    SERVICE_NAME = 'etherdelta.blockeeper'
    TENANT = 'ea23b9ad-a3ca-4936-8613-68446bd85dde'
    SERVICE_PRINCIPAL = credentials('SERVICE_PRINCIPAL')
    KUBERNETES_KEY = credentials('kubernetes-rsa')
  }

  stages {
    stage('Package') {
      environment {
        GEMFURY_MIRROR_URL = credentials('GEMFURY_MIRROR_URL')
      }
      steps {
        sh './ci/pipelines/package.sh'
      }
    }

    stage('Publish') {
      environment {
        ACR = credentials('AzureDockerRegistry')
      }
      steps {
        sh './centrality.deploy/publish.sh'
      }
    }

    stage('Dev Deploy') {
      environment {
        ENV = 'dev'
        SUBSCRIPTION_ID = '93a8e567-e173-4154-93fc-5b60248c8706'
        CLUSTER_URL = 'https://centrality-dev-master.australiasoutheast.cloudapp.azure.com'
      }
      steps {
        sh './centrality.deploy/deploy.sh'
      }
    }

    stage('Clear Docker Remains'){
        steps {
            sh 'docker run --rm -v /var/run/docker.sock:/var/run/docker.sock zzrot/docker-clean'
        }
    }
  }
}